import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import AuthProvider from "@/context/AuthProvider";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";

// import AuthProvider from "@/context/AuthProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <AuthProvider>
        <body
          suppressHydrationWarning
          className={`${geistSans.variable} ${geistMono.variable} bg-[#faf8f9] antialiased`}
        >
          {" "}
          {/* navbar */}
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
          <ToastContainer autoClose={700}></ToastContainer>
        </body>
      </AuthProvider>
    </html>
  );
}
